services:
  sonarr:
    container_name: arch-sonarr
    # image: sonarr
    build: .
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - /mnt/wd_white/downloads:/media
      - data:/var/lib/sonarr
volumes:
  data:
