services:
  sonarr:
    container_name: sonarr
    image: ghcr.io/thelovinator1/sonarr:master
    # build: .
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - /mnt/wd_white/downloads:/media
      - data:/var/lib/sonarr
volumes:
  data:
